name: Caliptra Security
run-name: caliptra-ci-5578s1
on:
  pull_request:
    branches: [dev]
  workflow_dispatch:
    inputs:
      client_payload:
        description: The Client payload
        required: true

permissions:
  contents: read
  security-events: write
  pull-requests: write
  packages: read

jobs:
  caliptra-ci-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Caliptra
        uses: caliptrasecurity/caliptra-security-action@main
        with:
          github_context: ${{ toJSON(github) }}
          inputs_context: ${{ toJSON(inputs) }}